apiVersion: v1
kind: Service
metadata:
  name: chat-backend-Service
spec:
  type: NodePort
  selector:
    app: caht-backend
  ports:
    - port: 8000 # The internal port of the app running
      name: service-port
      targetPort: 8000 # The port mapped to the POD /container
      nodePort: 30005 # The external service/browser reaches our app in this portnumber

##Useful commands
# kubectl get pods --show-labels
# kubectl describe pod <pod-name>
# minikube service backend-service --url minikube might map the port to different port, even though the nodePort is defineddifferently. It exposed url and port can be checked with this command